#pragma once

#define MEM_MAJOR		1
#define TTY_MAJOR		4
#define TTYAUX_MAJOR		5

#define UNIX98_PTY_MASTER_MAJOR	128
#define UNIX98_PTY_MAJOR_COUNT	8
#define UNIX98_PTY_SLAVE_MAJOR	(UNIX98_PTY_MASTER_MAJOR+UNIX98_PTY_MAJOR_COUNT)
